% Lowpass filter
rp=0.15;
rs=60;
p=1500;
s=3000;
fs=7000;
wp=(p*2)./fs;
ws=(s*2)./fs;
[nl,wl]=buttord(wp,ws,rp,rs,'s');
[zl,pl,kl]=butter(nl,wl);
[b,a]=butter(nl,wl,'s');
w=0:0.01:2*pi;
[h,wo]=freqs(b,a,w);
m=20*log10(abs(h));
an=angle(h);
subplot(2,1,1);
plot(wo/pi,m);
xlabel("Normalised Frequency");
ylabel("Gain in dB");
subplot(2,1,2);
plot(wo/pi,an);
xlabel("Normalised Frequency");
ylabel("Phase in Radians");
sgtitle(sprintf('n= %d Order Lowpass Butterworth Filter',nl));
figure;

% Highpass filter
rp=0.2;
rs=40;
p=2000;
s=3500;
fs=6000;
wp=(p*2)./fs;
ws=(s*2)./fs;
[nh,wh]=buttord(wp,ws,rp,rs,'s');
[zh,ph,kh]=butter(nh,wh,'high','s');
[b,a]=butter(nl,wl,'high','s');
w=0:0.01:2*pi;
[h,wo]=freqs(b,a,w);
m=20*log10(abs(h));
an=angle(h);
subplot(2,1,1);
plot(wo/pi,m);
xlabel("Normalised Frequency");
ylabel("Gain in dB");
subplot(2,1,2);
plot(wo/pi,an);
xlabel("Normalised Frequency");
ylabel("Phase in Radians");
sgtitle(sprintf('n= %d Order Highpass Butterworth Filter',nh));